const OmutatsuButtonInfoList = [
  {
    fileName: 'v3A7O6rhylY_komike',
    display: 'コミケぇ↑',
    kanaOrder: 'こみけぇ',
    streamId: 'v3A7O6rhylY',
  },
  {
    fileName: 'v3A7O6rhylY_wenwen',
    display: 'うぇーん',
    kanaOrder: 'うぇーん',
    streamId: 'v3A7O6rhylY',
  },
  {
    fileName: 'v3A7O6rhylY_komikedesuyo',
    display: 'コミケですよコミケぇ',
    kanaOrder: 'こみけですよこみけぇ',
    streamId: 'v3A7O6rhylY',
  },
  {
    fileName: 'v3A7O6rhylY_toiukotode',
    display: 'ということで',
    kanaOrder: 'ということで',
    streamId: 'v3A7O6rhylY',
  },
  {
    fileName: 'v3A7O6rhylY_batiboko',
    display: 'バチボコ怒られまして',
    kanaOrder: 'ばちぼこおこられまして',
    streamId: 'v3A7O6rhylY',
  },
  {
    fileName: 'v3A7O6rhylY_boroboro',
    display: 'ぼろぼろぼろぼろ',
    kanaOrder: 'ぼろぼろぼろぼろ',
    streamId: 'v3A7O6rhylY',
  },
  {
    fileName: 'v3A7O6rhylY_genkidesuka',
    display: 'みんな元気ですかあ',
    kanaOrder: 'みんなげんきですかあ',
    streamId: 'v3A7O6rhylY',
  },
  {
    fileName: 'v3A7O6rhylY_omaedattanoka',
    display: 'あぁ～お前だったのかぁ',
    kanaOrder: 'あぁ～おまえだったのかぁ',
    streamId: 'v3A7O6rhylY',
  },
  {
    fileName: 'v3A7O6rhylY_omae',
    display: 'おm…お前ｯ！…おまえ～',
    kanaOrder: 'おま…おまえっ！…おまえ～',
    streamId: 'v3A7O6rhylY',
  },
  {
    fileName: 'v3A7O6rhylY_konbanha',
    display: 'こんばんはいらっしゃい',
    kanaOrder: 'こんばんはいらっしゃい',
    streamId: 'v3A7O6rhylY',
  },
  {
    fileName: 'v3A7O6rhylY_dededon',
    display: 'デデドン！',
    kanaOrder: 'ででどん！',
    streamId: 'v3A7O6rhylY',
  },
  {
    fileName: 'P2Sjpd6T1Cw_korean',
    display: 'おむたつイムニダ～',
    kanaOrder: 'おむたついむにだ～',
    streamId: 'P2Sjpd6T1Cw',
  },
  {
    fileName: 'P2Sjpd6T1Cw_nemui',
    display: 'ほんとにねむいの…',
    kanaOrder: 'ほんとにねむいの…',
    streamId: 'P2Sjpd6T1Cw',
  },
  {
    fileName: 'P2Sjpd6T1Cw_wakaru',
    display: 'わかる！',
    kanaOrder: 'わかる！',
    streamId: 'P2Sjpd6T1Cw',
  },
  {
    fileName: 'P2Sjpd6T1Cw_amamama',
    display: 'あむあむあむあむ',
    kanaOrder: 'あむあむあむあむ',
    streamId: 'P2Sjpd6T1Cw',
  },
  {
    fileName: 'P2Sjpd6T1Cw_hontoniyokunai',
    display: 'ほんとによくないよね',
    kanaOrder: 'ほんとによくないよね',
    streamId: 'P2Sjpd6T1Cw',
  },
  {
    fileName: 'P2Sjpd6T1Cw_nandenan',
    display: 'なんでなんすかねェ',
    kanaOrder: 'なんでなんすかねぇ',
    streamId: 'P2Sjpd6T1Cw',
  },
  {
    fileName: 'P2Sjpd6T1Cw_oregaomutatsuda',
    display: '俺がおむたつだ！',
    kanaOrder: 'おれがおむたつだ！',
    streamId: 'P2Sjpd6T1Cw',
  },
  {
    fileName: 'P2Sjpd6T1Cw_yurusenaitteba',
    display: '許せないってばよ',
    kanaOrder: 'ゆるせないってばよ',
    streamId: 'P2Sjpd6T1Cw',
  },
  {
    fileName: 'P2Sjpd6T1Cw_sugoi',
    display: 'え～～すご～～い',
    kanaOrder: 'え～～すご～～い',
    streamId: 'P2Sjpd6T1Cw',
  },
  {
    fileName: 'P2Sjpd6T1Cw_tugihakiminoban',
    display: '次は君の番だ',
    kanaOrder: 'つぎはきみのばんだ',
    streamId: 'P2Sjpd6T1Cw',
  },
  {
    fileName: 'P2Sjpd6T1Cw_tyutyutyutyu',
    display: 'ﾁｭﾁｭﾁｭﾁｭﾁｭ♡ｱﾘｶﾞﾄ!',
    kanaOrder: 'ちゅちゅちゅちゅちゅ♡ありがと！',
    streamId: 'P2Sjpd6T1Cw',
  },
  {
    fileName: 'P2Sjpd6T1Cw_uretiureti',
    display: 'ｳﾚﾁ…ｳﾚﾁ…',
    kanaOrder: 'うれち…うれち…',
    streamId: 'P2Sjpd6T1Cw',
  },
  {
    fileName: 'P2Sjpd6T1Cw_wakatterundayo',
    display: 'ヮ~わかってるんだよぉ',
    kanaOrder: 'わ～わかってるんだよぉ',
    streamId: 'P2Sjpd6T1Cw',
  },
  {
    fileName: 'P2Sjpd6T1Cw_sukuttyatta',
    display: 'わたし救っちゃったの？',
    kanaOrder: 'わたしすくっちゃったの？',
    streamId: 'P2Sjpd6T1Cw',
  },
  {
    fileName: 'P2Sjpd6T1Cw_sukuitai',
    display: '救いたい、その命',
    kanaOrder: 'すくいたい、そのいのち',
    streamId: 'P2Sjpd6T1Cw',
  },
  {
    fileName: 'P2Sjpd6T1Cw_naniwoitteiruka',
    display: 'ﾁｮ何を言っているか',
    kanaOrder: 'ちょなにをいっているか',
    streamId: 'P2Sjpd6T1Cw',
  },
  {
    fileName: 'P2Sjpd6T1Cw_hazukashi',
    display: 'ﾊｽﾞｶｼｲ',
    kanaOrder: 'はずかしい',
    streamId: 'P2Sjpd6T1Cw',
  },
  {
    fileName: 'P2Sjpd6T1Cw_akatyanjan',
    display: 'ｱｶﾁｬﾝじゃん',
    kanaOrder: 'あかちゃんじゃん',
    streamId: 'P2Sjpd6T1Cw',
  },
  {
    fileName: 'P2Sjpd6T1Cw_raisenikitai',
    display: '来世に期待',
    kanaOrder: 'らいせにきたい',
    streamId: 'P2Sjpd6T1Cw',
  },
  {
    fileName: 'Bgfc0zApsXs_tetetete',
    display: 'てーててて♪',
    kanaOrder: 'てーててて',
    streamId: 'Bgfc0zApsXs',
  },
  {
    fileName: 'Bgfc0zApsXs_atisugina',
    display: 'あちすぎな、世界',
    kanaOrder: 'あちすぎな、せかい',
    streamId: 'Bgfc0zApsXs',
  },
  {
    fileName: 'Bgfc0zApsXs_dokidoki',
    display: 'ドキドキ、ドキドキ',
    kanaOrder: 'どきどき、どきどき',
    streamId: 'Bgfc0zApsXs',
  },
  {
    fileName: 'Bgfc0zApsXs_asekusai',
    display: 'おむたつさん汗臭ぁ～い',
    kanaOrder: 'おむたつさんあせくさぁ～い',
    streamId: 'Bgfc0zApsXs',
  },
  {
    fileName: 'Bgfc0zApsXs_koxnnitiha',
    display: 'こ゛ん゛に゛ち゛は゛',
    kanaOrder: 'ごんにぢば',
    streamId: 'Bgfc0zApsXs',
  },
  {
    fileName: 'Bgfc0zApsXs_prprprpr',
    display: 'ペロペロprprprpr',
    kanaOrder: 'ぺろぺろぺろ',
    streamId: 'Bgfc0zApsXs',
  },
  {
    fileName: 'Bgfc0zApsXs_nandeowaa',
    display: 'な、なんで…ｳﾜｧ',
    kanaOrder: 'な、なんで…うわぁ',
    streamId: 'Bgfc0zApsXs',
  },
  {
    fileName: 'Bgfc0zApsXs_madatarinai',
    display: 'まだ足りない',
    kanaOrder: 'まだたりない',
    streamId: 'Bgfc0zApsXs',
  },
  {
    fileName: 'Bgfc0zApsXs_nandexe',
    display: 'なんで！？どーして！？',
    kanaOrder: 'なんで！？どーして！？',
    streamId: 'Bgfc0zApsXs',
  },
  {
    fileName: 'Bgfc0zApsXs_syouganaina',
    display: 'ｼｮｰｶﾞﾅｲﾅｧｰ',
    kanaOrder: 'しょーがないなぁー',
    streamId: 'Bgfc0zApsXs',
  },
  {
    fileName: 'Bgfc0zApsXs_tanonda',
    display: '頼んだ',
    kanaOrder: 'たのんだ',
    streamId: 'Bgfc0zApsXs',
  },
  {
    fileName: 'Bgfc0zApsXs_mikunegimashi',
    display: 'ﾐｸﾐｸﾈｷﾞﾈｷﾞﾏｼﾏｼ',
    kanaOrder: 'みくみくねぎねぎましまし',
    streamId: 'Bgfc0zApsXs',
  },
  {
    fileName: 'Bgfc0zApsXs_mikunegidekomashi',
    display: 'ﾐｸﾐｸﾈｷﾞﾈｷﾞﾃﾞｺﾃﾞｺﾏｼﾏｼ',
    kanaOrder: 'みくみくねぎねぎでこでこましまし',
    streamId: 'Bgfc0zApsXs',
  },
  {
    fileName: 'Bgfc0zApsXs_okutiyuruyuru',
    display: 'これは私のお口がゆるゆるだからです',
    kanaOrder: 'これはわたしのおくちがゆるゆるだからです',
    streamId: 'Bgfc0zApsXs',
  },
  {
    fileName: 'Bgfc0zApsXs_shukurimu-retasu',
    display: 'シュークリームのシューはレタスって意味（キリッ）',
    kanaOrder: 'しゅーくりーむのしゅーはれたすっていみ',
    streamId: 'Bgfc0zApsXs',
  },
  {
    fileName: 'Bgfc0zApsXs_shukurimu-kyabetsu',
    display: 'シュークリームのシューはレタスじゃなくてキャベツでした',
    kanaOrder: 'しゅーくりーむのしゅーはれたすではなくきゃべつでした',
    streamId: 'Bgfc0zApsXs',
  },
]

export default OmutatsuButtonInfoList
